### PR TITLE
update keepcurrent to retry at most 5 times when failing to fetch source

### PR DESCRIPTION
**Pull request by joesis**
Depends on https://github.com/getlantern/keepcurrent/pull/1

### CODE REVIEW

**Comment by joesis** [comment]
I guess one decision to be made is - should it propagate the error to callers, or fail more soundly than printing an error?

**Comment by joesis** [comment]
Good idea. Will do!

**Comment by joesis** [comment]
Come to think of it again, having `Errors()` in the `Lookup` interface looks a bit distracted though. Let's hold off a bit until see a real necessity. Updated to the latest `keepcurrent`. Thanks for the review @hwh33 !

**Comment by hwh33** [comment]
Sounds good to me.  No problem!

**Pull request merged**
